name: "YAML Anchor Sample"

on:
  workflow_dispatch:
  push:
    paths: &paths
      - "src/**.py"
      - "Dockerfile"
      - "requirements.txt"
      - ".github/workflows/anchor_sample.yml"
    branches: &branches
      - main
  pull_request:
    paths: *paths
    branches: *branches

jobs:
  sample:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        run: |
          python src/a.py
